---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: win
autosplit: true
retryOnFailure: false
maxRetries: 1
concurrency: 1
env:
  PWTEST_SKIP_TEST_OUTPUT: 1
pre:
  - npm install
  - npx playwright install
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: static
  command: grep -lr 'test(' src/*
testRunnerCommand: npx playwright test $test -c playwright-ct.config.js --headed
jobLabel: [playwright-VanillaJS, win, autosplit] 
captureScreenRecordingForScenarios: true